/**
 * The pictures a student uncovers, as the home page shows them.
 *
 * ## Why this is a module and not markup
 *
 * Alt text is the part that gets skipped when images are typed straight into a
 * page, and here it does double duty: it is what a screen-reader user gets
 * instead of the picture, and it is most of what a web filter's classifier can
 * read on a JavaScript-rendered page. `sal0mander.com` is blocked by at least
 * one district as "categorized as Unknown", so ten sentences describing coral
 * reefs, castles and astrophotography are a stronger Education signal than the
 * images themselves.
 *
 * Keeping it in one array means a test can hold every entry to the same rule:
 * a real file, a same-origin path, and a description of the actual scene.
 *
 * ## Two images from the generated set are deliberately absent
 *
 * `panther_chameleon_rainforest` and `robot_alien_crystals` have jigsaw cut
 * lines painted into the pixels — a few hundred fake pieces baked into the
 * artwork. SAL0MANder's activities are nine pieces and Unity draws its own
 * edges, so those two would show a student one puzzle inside another and
 * promise a piece count the product does not have. They are good images and
 * the wrong images.
 *
 * ## What these are NOT
 *
 * Not tied to any activity. Unity owns which picture an activity uses, through
 * `imagePresetIndex` in `CreateDemoActivity`, so captioning one of these as
 * "the Integer Operations puzzle" would be a claim this repository cannot
 * check and would quietly go stale the moment a preset changed. They are shown
 * as what they are: a sample of the library.
 */
export const PUZZLE_PICTURE_CATEGORIES = [
  'Animals',
  'Fantasy',
  'Food',
  'Nature',
  'Places',
  'Space',
  'Vehicles',
] as const
export type PuzzlePictureCategory = (typeof PUZZLE_PICTURE_CATEGORIES)[number]

export type PuzzlePicture = {
  /**
   * Stable identifier, and what should be sent to Unity instead of an array
   * position.
   *
   * `ActivityData.imagePresetIndex` is positional — `0=Dog, 1=Cat, 2=Lotus`.
   * Reordering that array silently repoints every existing activity at a
   * different picture: no error, no warning, and a teacher discovers it when a
   * class opens the wrong puzzle. A key survives reordering, and an unknown key
   * can fail loudly instead.
   */
  readonly key: string
  /** Which board this fits. Unity's `BoardShape` has exactly three. */
  readonly shape: 'Square' | 'Portrait' | 'Landscape'
  /** Shown to the teacher in the picker. */
  readonly name: string
  /** A small, shared set of themes for browsing the library. */
  readonly category: PuzzlePictureCategory
  /** Same-origin path under `public/`. An external host would be one more domain a district has to allow. */
  readonly src: string
  /** Describes the scene. Never "puzzle image" — see the module note. */
  readonly alt: string
  /** Rendered aspect, so the grid can reserve space and not shift as images load. */
  readonly width: number
  readonly height: number
  /** Optional familiar search names and alternate spellings. */
  readonly searchTerms?: readonly string[]
  /** Verified photographic sources only; generated or unverified artwork has no photo credit. */
  readonly photoCredit?: {
    /** Original source title, when supplied by its creator. */
    readonly title?: string
    readonly author: string
    readonly source: string
    readonly license: string
    readonly licenseUrl: string
    readonly modifications?: string
  }
  /** Generated artwork is labeled separately and never enters the real-photo filter. */
  readonly artworkCredit?: {
    readonly creator: string
    readonly generation: 'AI-generated'
    readonly modifications?: string
  }
}

/**
 * A mix of fantasy, realistic wildlife, and educational scenes across Unity's
 * three board shapes. Full-quality masters stay separate from these compact
 * website previews; generated wildlife is identified in its description.
 */
export const PUZZLE_LIBRARY: readonly PuzzlePicture[] = [
  {
    key: 'salamander-forest',
    shape: 'Square',
    name: 'Forest guardian',
    category: 'Fantasy',
    src: '/images/library/square/fantasy/salamander_forest.webp',
    alt: 'Fantasy illustration of a bright-eyed black salamander with lime markings and small fins, perched on a mossy log beside glowing mushrooms and a forest waterfall.',
    width: 480,
    height: 480,
  },
  {
    key: 'red-panda',
    shape: 'Square',
    name: 'Red panda forest',
    category: 'Animals',
    src: '/images/library/square/wildlife/red_panda_forest.webp',
    alt: 'Realistic generated wildlife illustration of a red panda with russet fur and a long ringed tail resting on a mossy tree above a mountain forest.',
    width: 480,
    height: 480,
  },
  {
    key: 'snow-leopard',
    shape: 'Square',
    name: 'Snow leopard mountains',
    category: 'Animals',
    src: '/images/library/square/wildlife/snow_leopard_mountains.webp',
    alt: 'Realistic generated wildlife illustration of a young snow leopard with silver spotted fur and a thick curling tail on a rocky ledge in sunlit snowy mountains.',
    width: 480,
    height: 480,
  },
  {
    key: 'coral-reef',
    shape: 'Square',
    name: 'Coral reef',
    category: 'Animals',
    src: '/images/library/square/cartoon/coral_reef_marine_life.webp',
    alt: 'Illustration of a coral reef crowded with sea life — a green sea turtle, an octopus, clownfish in an anemone, a moray eel and a crab among branching corals and sponges.',
    width: 640,
    height: 640,
  },
  {
    key: 'colosseum',
    shape: 'Square',
    name: 'The Colosseum',
    category: 'Places',
    src: '/images/library/square/photo/colosseum_rome_aerial.webp',
    alt: 'Aerial photograph of the Roman Colosseum at golden hour, with the Arch of Constantine and the surrounding streets and rooftops of Rome.',
    width: 640,
    height: 640,
  },
  {
    key: 'bakery',
    shape: 'Landscape',
    name: 'Mouse bakery',
    category: 'Fantasy',
    src: '/images/library/landscape/cartoon/magical_bakery_workshop.webp',
    alt: 'Illustration of three mice in aprons baking in a stone-walled bakery, with a wood-fired oven, shelves of breads, tarts and iced cakes, and jars of preserves.',
    width: 640,
    height: 478,
  },
  {
    key: 'saturn',
    shape: 'Landscape',
    name: 'Saturn and nebula',
    category: 'Space',
    src: '/images/library/landscape/photo/saturn_nebula_astrophotography.webp',
    alt: 'Space scene showing Saturn and its rings against a starfield, with spiral galaxies and pink and blue nebula clouds.',
    width: 640,
    height: 478,
  },
  {
    key: 'dragon-castle',
    shape: 'Portrait',
    name: 'Dragon castle',
    category: 'Fantasy',
    src: '/images/library/portrait/cartoon/floating_island_castle_dragon.webp',
    alt: 'Illustration of a fairy-tale castle on a floating island, a green dragon perched on one tower, hot-air balloons and waterfalls spilling into the clouds below.',
    width: 640,
    height: 857,
  },
  {
    key: 'highland-castle',
    shape: 'Portrait',
    name: 'Highland castle',
    category: 'Places',
    src: '/images/library/portrait/photo/scottish_highland_stone_fortress.webp',
    alt: 'Photograph of a stone castle on a Scottish loch at sunset, reached by an arched bridge, with heather in the foreground and mountains behind.',
    width: 640,
    height: 857,
  },
  {
    key: 'autumn-woodland',
    shape: 'Landscape',
    name: 'Autumn woodland village',
    category: 'Fantasy',
    src: '/images/library/custom-wide/cartoon/enchanted_autumn_woodland.webp',
    alt: 'Illustration of glowing mushroom cottages beside a winding stream, with wooden bridges, foxes, hedgehogs and owls beneath golden autumn trees.',
    width: 640,
    height: 429,
  },
  {
    key: 'dinosaur-valley',
    shape: 'Landscape',
    name: 'Dinosaur valley',
    category: 'Animals',
    src: '/images/library/custom-wide/cartoon/dinosaur_jurassic_valley.webp',
    alt: 'Illustration of long-necked and horned dinosaurs beside a tropical river, with a waterfall, flying pterosaur and smoking volcano under a peach-colored sky.',
    width: 640,
    height: 357,
  },
  {
    key: 'alpine-lake',
    shape: 'Landscape',
    name: 'Alpine lake and wildflowers',
    category: 'Nature',
    src: '/images/library/custom-wide/photo/alpine_lake_wildflowers.webp',
    alt: 'Realistic generated landscape of a turquoise alpine lake reflecting snowy mountains, with a wooden dock, evergreen trees and red, yellow and purple wildflowers.',
    width: 640,
    height: 429,
  },
  {
    key: 'rainforest-macaws',
    shape: 'Landscape',
    name: 'Rainforest macaws',
    category: 'Animals',
    src: '/images/library/custom-wide/photo/amazon_rainforest_macaws.webp',
    alt: 'Realistic generated wildlife scene with scarlet macaws and black toucans among orchids and broad green leaves, overlooking a rainforest river at sunrise.',
    width: 640,
    height: 357,
  },
  {
    key: 'steampunk-airship',
    shape: 'Portrait',
    name: 'Sunset airship',
    category: 'Vehicles',
    src: '/images/library/custom-tall/cartoon/steampunk_flying_airship.webp',
    alt: 'Illustration of an ornate brass and wooden airship with balloons, propellers, glowing windows and blue engines, surrounded by mechanical birds in sunset clouds.',
    width: 640,
    height: 954,
  },
  {
    key: 'mountain-steam-train',
    shape: 'Portrait',
    name: 'Mountain steam train',
    category: 'Vehicles',
    src: '/images/library/custom-tall/photo/steam_locomotive_mountain_viaduct.webp',
    alt: 'Realistic generated landscape of a black steam locomotive and red passenger carriages crossing a curved stone viaduct, with autumn trees, mountains and a waterfall.',
    width: 640,
    height: 954,
  },
  {
    key: 'sleeping-puppies',
    searchTerms: ['puppy', 'puppies', 'dogs'],
    shape: 'Landscape',
    name: 'Sleeping puppies',
    category: 'Animals',
    src: '/images/library/photos/sleeping-puppies.webp',
    alt: 'Photograph of four small tan, brown and white puppies curled together asleep inside a cardboard box, with their paws and tails overlapping.',
    width: 960,
    height: 720,
    photoCredit: {
      author: 'Saral Shots',
      source: 'https://commons.wikimedia.org/wiki/File:Sleeping_puppies.jpg',
      license: 'CC0 1.0',
      licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    },
  },
  {
    key: 'puggle-puppy',
    searchTerms: ['puppy', 'puppies', 'dogs'],
    shape: 'Landscape',
    name: 'Puggle puppy in flowers',
    category: 'Animals',
    src: '/images/library/photos/puggle-puppy.webp',
    alt: 'Photograph of a tan puggle puppy with floppy brown ears and a dark muzzle sitting in green grass among bright yellow dandelion flowers.',
    width: 960,
    height: 720,
    photoCredit: {
      author: 'Jennagu',
      source: 'https://commons.wikimedia.org/wiki/File:Puggle_puppy.jpg',
      license: 'Public domain',
      licenseUrl: 'https://commons.wikimedia.org/wiki/File:Puggle_puppy.jpg#Licensing',
    },
  },
  {
    key: 'orange-indy-race-car',
    searchTerms: ['racecar', 'racecars', 'race cars', 'racing', 'IndyCar'],
    shape: 'Landscape',
    name: 'Orange Indy race car',
    category: 'Vehicles',
    src: '/images/library/photos/orange-indy-race-car.webp',
    alt: 'Photograph of Pato O’Ward’s orange and black number 5 open-wheel race car rounding the gray Mid-Ohio track, bordered by green grass.',
    width: 960,
    height: 540,
    photoCredit: {
      author: 'YellowstoneTrinity / William Zhang',
      source: 'https://commons.wikimedia.org/wiki/File:OWard_MidOhio_2024_FastSix.jpg',
      license: 'CC0 1.0',
      licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    },
  },
  {
    key: 'red-indy-race-car',
    searchTerms: ['racecar', 'racecars', 'race cars', 'racing', 'IndyCar'],
    shape: 'Landscape',
    name: 'Red Indy race car',
    category: 'Vehicles',
    src: '/images/library/photos/red-indy-race-car.webp',
    alt: 'Photograph of Scott McLaughlin’s red and black number 3 open-wheel race car speeding past green grass and a safety barrier at Mid-Ohio.',
    width: 960,
    height: 540,
    photoCredit: {
      author: 'YellowstoneTrinity / William Zhang',
      source: 'https://commons.wikimedia.org/wiki/File:Scott_McLaughlin_MidOhio_2024.jpg',
      license: 'CC0 1.0',
      licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    },
  },
  {
    key: 'art-pug',
    name: 'Pug puppy',
    category: 'Animals',
    alt: 'AI-generated realistic image of a fawn pug puppy with a black muzzle sitting on a garden path surrounded by flowers.',
    searchTerms: ['pug', 'puppy', 'puppies', 'dog', 'dogs', 'cute', 'aww'],
    shape: 'Square',
    src: '/images/library/rewards/art-pug.webp',
    width: 900,
    height: 900,
  },
  {
    key: 'art-dachshund',
    name: 'Dachshund puppy',
    category: 'Animals',
    alt: 'AI-generated realistic image of a red dachshund puppy with floppy ears and a long body standing on a flowering garden path.',
    searchTerms: [
      'dachshund',
      'dachshunds',
      'wiener dog',
      'sausage dog',
      'puppy',
      'dog',
      'cute',
      'aww',
    ],
    shape: 'Square',
    src: '/images/library/rewards/art-dachshund.webp',
    width: 900,
    height: 900,
  },
  {
    key: 'art-ginger-tabby',
    name: 'Ginger tabby kitten',
    category: 'Animals',
    alt: 'AI-generated realistic image of an orange tabby kitten with white paws stretching on a stone path between garden flowers.',
    searchTerms: [
      'cat',
      'cats',
      'kitten',
      'kittens',
      'orange cat',
      'ginger',
      'tabby',
      'cute',
      'aww',
    ],
    shape: 'Square',
    src: '/images/library/rewards/art-ginger-tabby.webp',
    width: 900,
    height: 900,
  },
  {
    key: 'art-tuxedo-cat',
    name: 'Tuxedo kitten',
    category: 'Animals',
    alt: 'AI-generated realistic image of a black-and-white tuxedo kitten tilting its head while sitting on a wooden garden bench.',
    searchTerms: ['cat', 'cats', 'kitten', 'kittens', 'tuxedo', 'black and white', 'cute', 'aww'],
    shape: 'Square',
    src: '/images/library/rewards/art-tuxedo-cat.webp',
    width: 900,
    height: 900,
  },
  {
    key: 'art-tiger',
    name: 'Tiger forest stream',
    category: 'Animals',
    alt: 'AI-generated realistic image of a Bengal tiger walking calmly on mossy rocks beside a forest stream and green ferns.',
    searchTerms: ['tiger', 'tigers', 'big cat', 'jungle', 'wildlife', 'cool', 'wild'],
    shape: 'Square',
    src: '/images/library/rewards/art-tiger.webp',
    width: 900,
    height: 900,
  },
  {
    key: 'art-elephant',
    name: 'Elephant watering hole',
    category: 'Animals',
    alt: 'AI-generated realistic image of a young African elephant with its trunk curled beside a savanna watering hole in warm light.',
    searchTerms: ['elephant', 'elephants', 'safari', 'savanna', 'wildlife', 'cute', 'aww'],
    shape: 'Square',
    src: '/images/library/rewards/art-elephant.webp',
    width: 900,
    height: 900,
  },
  {
    key: 'art-lion',
    name: 'Lion on the rocks',
    category: 'Animals',
    alt: 'AI-generated realistic image of a male lion with a golden mane standing on a rock above sunlit savanna grass and acacia trees.',
    searchTerms: ['lion', 'lions', 'big cat', 'safari', 'savanna', 'wildlife', 'cool', 'wild'],
    shape: 'Square',
    src: '/images/library/rewards/art-lion.webp',
    width: 900,
    height: 900,
  },
  {
    key: 'art-mountain-lake',
    name: 'Mountains and turquoise lake',
    category: 'Nature',
    alt: 'AI-generated realistic landscape of snow-capped mountain peaks reflected in a turquoise lake, with pines, wildflowers and foreground rocks.',
    searchTerms: [
      'mountain',
      'mountains',
      'lake',
      'alpine',
      'snow',
      'landscape',
      'relaxing',
      'beautiful',
    ],
    shape: 'Square',
    src: '/images/library/rewards/art-mountain-lake.webp',
    width: 900,
    height: 900,
  },
  {
    key: 'art-tropical-beach',
    name: 'Tropical beach',
    category: 'Nature',
    alt: 'AI-generated realistic landscape of a sunny tropical beach with turquoise water, gentle waves, palm trees, rocks and shells on golden sand.',
    searchTerms: [
      'beach',
      'beaches',
      'ocean',
      'sea',
      'palms',
      'tropical',
      'landscape',
      'relaxing',
      'beautiful',
    ],
    shape: 'Square',
    src: '/images/library/rewards/art-tropical-beach.webp',
    width: 900,
    height: 900,
  },
  {
    key: 'photo-lion-cub',
    name: 'Little lion in the grass',
    category: 'Animals',
    alt: 'Photograph of a young lion climbs through tall green grass, with its rounded ears and face in profile.',
    searchTerms: ['lion', 'cub', 'baby', 'cute', 'wildlife', 'grass', 'safari'],
    photoCredit: {
      title: 'Lion Cub',
      author: 'William Warby',
      source: 'https://commons.wikimedia.org/wiki/File:Lion_Cub_(2404636221).jpg',
      license: 'CC BY 2.0',
      licenseUrl: 'https://creativecommons.org/licenses/by/2.0/',
      modifications: 'Resized; WebP format',
    },
    shape: 'Landscape',
    src: '/images/library/rewards/photo-lion-cub.webp',
    width: 900,
    height: 675,
  },
  {
    key: 'photo-tiger-looking',
    name: 'Tiger looking at you',
    category: 'Animals',
    alt: 'Photograph of an orange-and-black tiger faces the camera with its mouth slightly open against leafy greenery.',
    searchTerms: ['tiger', 'stripes', 'big cat', 'expressive', 'cool', 'wildlife'],
    photoCredit: {
      title: 'Tiger Looking at Me',
      author: 'Amaury Laporte',
      source: 'https://commons.wikimedia.org/wiki/File:Tiger_Looking_at_Me.jpg',
      license: 'CC BY 2.0',
      licenseUrl: 'https://creativecommons.org/licenses/by/2.0/',
      modifications: 'Resized; WebP format',
    },
    shape: 'Landscape',
    src: '/images/library/rewards/photo-tiger-looking.webp',
    width: 900,
    height: 600,
  },
  {
    key: 'photo-bear-cub',
    name: 'Curious bear cub',
    category: 'Animals',
    alt: 'Photograph of a fluffy brown bear cub looks toward the camera against softly blurred green plants.',
    searchTerms: ['bear', 'cub', 'baby', 'cute', 'curious', 'fluffy', 'alaska'],
    photoCredit: {
      author: 'Lisa Hupp / U.S. Fish and Wildlife Service',
      source: 'https://commons.wikimedia.org/wiki/File:Bear_cub_(28661807722).jpg',
      license: 'Public domain',
      licenseUrl: 'https://commons.wikimedia.org/wiki/Template:PD-USGov-FWS',
      modifications: 'Resized; WebP format',
    },
    shape: 'Portrait',
    src: '/images/library/rewards/photo-bear-cub.webp',
    width: 600,
    height: 900,
  },
  {
    key: 'photo-rainbow-ice-cream',
    name: 'Rainbow-sprinkle ice cream',
    category: 'Food',
    alt: 'Photograph of a waffle cone holds a round scoop covered in bright multicolored sprinkles against a turquoise background.',
    searchTerms: [
      'ice cream',
      'cone',
      'sprinkles',
      'rainbow',
      'colorful',
      'dessert',
      'sweet',
      'treat',
    ],
    photoCredit: {
      title: 'Free Rainbow Sprinkle Ice Cream Cone Creative Commons',
      author: 'D. Sharon Pruitt',
      source: 'https://commons.wikimedia.org/wiki/File:Ice_cream_cone.jpg',
      license: 'CC BY 2.0',
      licenseUrl: 'https://creativecommons.org/licenses/by/2.0/',
      modifications: 'Resized; WebP format',
    },
    shape: 'Portrait',
    src: '/images/library/rewards/photo-rainbow-ice-cream.webp',
    width: 867,
    height: 900,
  },
  {
    key: 'photo-cat-laptop-yawn',
    name: 'Cat takes over the laptop',
    category: 'Animals',
    alt: 'Photograph of a Siamese-type cat yawns widely while sitting across an open laptop keyboard in a sepia-toned photograph.',
    searchTerms: ['cat', 'funny', 'yawn', 'sleepy', 'laptop', 'pet', 'expressive'],
    photoCredit: {
      author: 'acebrand',
      source: 'https://commons.wikimedia.org/wiki/File:Cat_on_laptop_yawning.jpg',
      license: 'CC0 1.0',
      licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
      modifications: 'Resized; WebP format',
    },
    shape: 'Landscape',
    src: '/images/library/rewards/photo-cat-laptop-yawn.webp',
    width: 900,
    height: 588,
  },
  {
    key: 'photo-golden-dog',
    name: 'Gentle golden retriever',
    category: 'Animals',
    alt: 'Photograph of a golden retriever sits on paving stones beside a textured wall and looks up toward the camera.',
    searchTerms: ['dog', 'golden retriever', 'cute', 'gentle', 'pet', 'puppy eyes', 'expressive'],
    photoCredit: {
      author: 'Jusotil_1943',
      source: 'https://commons.wikimedia.org/wiki/File:Dog_(41625601132).jpg',
      license: 'CC0 1.0',
      licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
      modifications: 'Resized; WebP format',
    },
    shape: 'Landscape',
    src: '/images/library/rewards/photo-golden-dog.webp',
    width: 900,
    height: 506,
  },
  {
    key: 'photo-mountain-lake-dusk',
    name: 'Mountain lake at dusk',
    category: 'Nature',
    alt: 'Photograph of a turquoise mountain lake winds below forested peaks beneath peach-colored evening clouds.',
    searchTerms: [
      'mountains',
      'lake',
      'sunset',
      'dusk',
      'beautiful',
      'peaceful',
      'landscape',
      'relaxing',
      'beautiful',
    ],
    photoCredit: {
      author: 'Burst',
      source: 'https://isorepublic.com/photo/mountain-lake-dusk/',
      license: 'CC0 1.0',
      licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
      modifications: 'Resized; WebP format',
    },
    shape: 'Portrait',
    src: '/images/library/rewards/photo-mountain-lake-dusk.webp',
    width: 695,
    height: 900,
  },
  {
    key: 'photo-tropical-beach',
    name: 'Palm-tree beach',
    category: 'Nature',
    alt: 'Photograph of tall palm trees cast shadows over pale sand beside a bright turquoise sea, with a few distant beachgoers.',
    searchTerms: [
      'beach',
      'ocean',
      'palms',
      'tropical',
      'sunshine',
      'beautiful',
      'vacation',
      'turquoise',
      'relaxing',
      'beautiful',
    ],
    photoCredit: {
      author: 'Matt Moloney',
      source: 'https://isorepublic.com/photo/tropical-beach-island/',
      license: 'CC0 1.0',
      licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
      modifications: 'Resized; WebP format',
    },
    shape: 'Landscape',
    src: '/images/library/rewards/photo-tropical-beach.webp',
    width: 900,
    height: 479,
  },
  {
    key: 'art-red-panda-waterfall',
    shape: 'Square',
    name: 'Red panda waterfall · AI artwork',
    category: 'Animals',
    src: '/images/library/rewards/art-red-panda-waterfall.webp',
    alt: 'AI-generated realistic artwork of a curious red panda standing on a mossy rock beside a small forest waterfall, ferns, golden leaves and a clear stream.',
    width: 720,
    height: 720,
    searchTerms: [
      'red panda',
      'wildlife',
      'waterfall',
      'forest',
      'stream',
      'cute',
      'scenic',
      'nature',
      'AI artwork',
    ],
  },
  {
    key: 'fictional-neon-tuner-v1',
    shape: 'Landscape',
    name: 'Neon Torque · AI artwork',
    category: 'Vehicles',
    src: '/images/library/ai/fictional-neon-tuner-v1.webp',
    alt: 'AI-generated concept artwork of a fictional blue tuner coupe at midnight, with bright neon reflections around the car.',
    width: 1024,
    height: 683,
    searchTerms: [
      'neon',
      'blue',
      'tuner',
      'midnight',
      'car',
      'cars',
      'racecar',
      'race cars',
      'fictional',
      'AI artwork',
    ],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'fictional-sunset-muscle-v1',
    shape: 'Landscape',
    name: 'Copper Thunder · AI artwork',
    category: 'Vehicles',
    src: '/images/library/ai/fictional-sunset-muscle-v1.webp',
    alt: 'AI-generated concept artwork of a fictional muscle car in warm sunset light, with its full body and wheels visible.',
    width: 1024,
    height: 683,
    searchTerms: [
      'copper',
      'muscle car',
      'sunset',
      'car',
      'cars',
      'racecar',
      'race cars',
      'fictional',
      'AI artwork',
    ],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'fictional-silver-supercar-v1',
    shape: 'Landscape',
    name: 'Silver Horizon · AI artwork',
    category: 'Vehicles',
    src: '/images/library/ai/fictional-silver-supercar-v1.webp',
    alt: 'AI-generated concept artwork of a fictional silver supercar in side profile, showing its low body and detailed wheels.',
    width: 1024,
    height: 683,
    searchTerms: [
      'silver',
      'supercar',
      'side view',
      'car',
      'cars',
      'racecar',
      'race cars',
      'fictional',
      'AI artwork',
    ],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'fictional-canyon-racer-side-v1',
    shape: 'Landscape',
    name: 'Canyon Circuit · side view · AI artwork',
    category: 'Vehicles',
    src: '/images/library/ai/fictional-canyon-racer-side-v1.webp',
    alt: 'AI-generated concept artwork of a fictional racing car seen from the side in a rugged canyon setting.',
    width: 1024,
    height: 683,
    searchTerms: [
      'canyon',
      'side view',
      'racer',
      'car',
      'cars',
      'racecar',
      'race cars',
      'fictional',
      'AI artwork',
    ],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'fictional-midnight-gt-v1',
    shape: 'Landscape',
    name: 'Midnight Current · AI artwork',
    category: 'Vehicles',
    src: '/images/library/ai/fictional-midnight-gt-v1.webp',
    alt: 'AI-generated concept artwork of a fictional GT sports car in side profile, illuminated against a midnight setting.',
    width: 1024,
    height: 683,
    searchTerms: [
      'midnight',
      'GT',
      'side view',
      'car',
      'cars',
      'racecar',
      'race cars',
      'fictional',
      'AI artwork',
    ],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'fictional-snow-rally-v1',
    shape: 'Landscape',
    name: 'Snowline Rally · AI artwork',
    category: 'Vehicles',
    src: '/images/library/ai/fictional-snow-rally-v1.webp',
    alt: 'AI-generated concept artwork of a fictional rally car in a wintry landscape, with snow around its wheels.',
    width: 1024,
    height: 683,
    searchTerms: [
      'snow',
      'rally',
      'winter',
      'car',
      'cars',
      'racecar',
      'race cars',
      'fictional',
      'AI artwork',
    ],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'fictional-canyon-racer-v1',
    shape: 'Landscape',
    name: 'Canyon Circuit · front view · AI artwork',
    category: 'Vehicles',
    src: '/images/library/ai/fictional-canyon-racer-v1.webp',
    alt: 'AI-generated concept artwork of a fictional racing car viewed from the front in a rugged canyon setting.',
    width: 1024,
    height: 683,
    searchTerms: [
      'canyon',
      'front view',
      'racer',
      'car',
      'cars',
      'racecar',
      'race cars',
      'fictional',
      'AI artwork',
    ],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'fictional-coastal-racer-v1',
    shape: 'Landscape',
    name: 'Coastal Charge · AI artwork',
    category: 'Vehicles',
    src: '/images/library/ai/fictional-coastal-racer-v1.webp',
    alt: 'AI-generated concept artwork of a fictional racing car beside a scenic coast, with the car clearly framed against the landscape.',
    width: 1024,
    height: 683,
    searchTerms: [
      'coast',
      'ocean',
      'racer',
      'car',
      'cars',
      'racecar',
      'race cars',
      'fictional',
      'AI artwork',
    ],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'ai-pug-playtime-v1',
    shape: 'Square',
    name: 'Pug playtime · AI artwork',
    category: 'Animals',
    src: '/images/library/ai/ai-pug-playtime-v1.webp',
    alt: 'AI-generated realistic artwork of two pug puppies on a green quilt, one tilting its head while the other rests on a yellow toy ball.',
    width: 1024,
    height: 1024,
    searchTerms: ['pug', 'pugs', 'puppy', 'puppies', 'dog', 'dogs', 'cute', 'funny', 'AI artwork'],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'ai-dachshund-garden-v1',
    shape: 'Square',
    name: 'Dachshund garden explorers · AI artwork',
    category: 'Animals',
    src: '/images/library/ai/ai-dachshund-garden-v1.webp',
    alt: 'AI-generated realistic artwork of a red dachshund sniffing a flower beside a small black-and-tan dachshund on a garden path lined with flowerpots.',
    width: 1024,
    height: 1024,
    searchTerms: [
      'dachshund',
      'dachshunds',
      'wiener dog',
      'sausage dog',
      'puppy',
      'puppies',
      'cute',
      'AI artwork',
    ],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'ai-kitten-mischief-v1',
    shape: 'Square',
    name: 'Kitten basket mischief · AI artwork',
    category: 'Animals',
    src: '/images/library/ai/ai-kitten-mischief-v1.webp',
    alt: 'AI-generated realistic artwork of an orange-and-white kitten peeking from a wicker basket while a gray-and-white kitten plays with a red ball on a blue rug.',
    width: 1024,
    height: 1024,
    searchTerms: ['kitten', 'kittens', 'cat', 'cats', 'basket', 'cute', 'funny', 'AI artwork'],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'ai-golden-retriever-orchard-v1',
    shape: 'Square',
    name: 'Orchard Sunbeam · AI artwork',
    category: 'Animals',
    src: '/images/library/ai/ai-golden-retriever-orchard-v1.webp',
    alt: 'AI-generated realistic artwork of a golden retriever resting in an orchard among apples, grass and sunlit trees.',
    width: 1024,
    height: 1024,
    searchTerms: ['golden retriever', 'dog', 'puppy', 'orchard', 'apples', 'cute', 'AI artwork'],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'ai-french-bulldog-box-v1',
    shape: 'Square',
    name: 'Curious Little Unboxer · AI artwork',
    category: 'Animals',
    src: '/images/library/ai/ai-french-bulldog-box-v1.webp',
    alt: 'AI-generated realistic artwork of a curious French bulldog resting its front paws on a cardboard box in a cozy room.',
    width: 1024,
    height: 1024,
    searchTerms: [
      'French bulldog',
      'frenchie',
      'dog',
      'puppy',
      'box',
      'funny',
      'cute',
      'AI artwork',
    ],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'ai-corgi-beach-v1',
    shape: 'Square',
    name: 'Corgi Coast Explorer · AI artwork',
    category: 'Animals',
    src: '/images/library/ai/ai-corgi-beach-v1.webp',
    alt: 'AI-generated realistic artwork of a corgi exploring a sandy beach with shells, paw prints and distant shoreline rocks.',
    width: 1024,
    height: 1024,
    searchTerms: ['corgi', 'dog', 'puppy', 'beach', 'ocean', 'cute', 'AI artwork'],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'ai-beagle-porch-v1',
    shape: 'Square',
    name: 'Porchside Pal · AI artwork',
    category: 'Animals',
    src: '/images/library/ai/ai-beagle-porch-v1.webp',
    alt: 'AI-generated realistic artwork of a beagle resting on a porch mat beside flowers and a garden.',
    width: 1024,
    height: 1024,
    searchTerms: ['beagle', 'dog', 'puppy', 'porch', 'cute', 'AI artwork'],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'ai-german-shepherd-meadow-v1',
    shape: 'Square',
    name: 'Meadow Guardian · AI artwork',
    category: 'Animals',
    src: '/images/library/ai/ai-german-shepherd-meadow-v1.webp',
    alt: 'AI-generated realistic artwork of a German shepherd sitting in a meadow beside a path, wildflowers and distant hills.',
    width: 1024,
    height: 1024,
    searchTerms: ['German shepherd', 'dog', 'meadow', 'wildflowers', 'cute', 'AI artwork'],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'ai-husky-snow-v1',
    shape: 'Square',
    name: 'Snow Day Invitation · AI artwork',
    category: 'Animals',
    src: '/images/library/ai/ai-husky-snow-v1.webp',
    alt: 'AI-generated realistic artwork of a husky in a playful bow in the snow, with trees and distant mountains behind.',
    width: 1024,
    height: 1024,
    searchTerms: ['husky', 'dog', 'puppy', 'snow', 'winter', 'play', 'cute', 'AI artwork'],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'ai-poodle-garden-v1',
    shape: 'Square',
    name: 'Garden Nose Knows · AI artwork',
    category: 'Animals',
    src: '/images/library/ai/ai-poodle-garden-v1.webp',
    alt: 'AI-generated realistic artwork of an apricot poodle looking toward a flower beside garden pots and a stone path.',
    width: 1024,
    height: 1024,
    searchTerms: ['poodle', 'dog', 'puppy', 'garden', 'flowers', 'cute', 'AI artwork'],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'ai-jack-russell-planter-v1',
    shape: 'Square',
    name: 'The Planter Mystery · AI artwork',
    category: 'Animals',
    src: '/images/library/ai/ai-jack-russell-planter-v1.webp',
    alt: 'AI-generated realistic artwork of a Jack Russell terrier tilting its head beside a tipped empty planter and scattered garden soil.',
    width: 1024,
    height: 1024,
    searchTerms: [
      'Jack Russell',
      'terrier',
      'dog',
      'puppy',
      'planter',
      'funny',
      'cute',
      'AI artwork',
    ],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'ai-maine-coon-window-v1',
    shape: 'Square',
    name: 'Window-seat Maine Coon · AI artwork',
    category: 'Animals',
    src: '/images/library/ai/ai-maine-coon-window-v1.webp',
    alt: 'AI-generated realistic artwork of a fluffy brown tabby Maine Coon sitting on a wooden window seat, with a bushy tail and a garden outside.',
    width: 1024,
    height: 1024,
    searchTerms: ['Maine Coon', 'cat', 'kitten', 'fluffy', 'window', 'cute', 'AI artwork'],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'ai-ragdoll-quilt-v1',
    shape: 'Square',
    name: 'Ragdoll quilt cuddle · AI artwork',
    category: 'Animals',
    src: '/images/library/ai/ai-ragdoll-quilt-v1.webp',
    alt: 'AI-generated realistic artwork of a fluffy blue-eyed ragdoll kitten relaxing on a colorful patchwork quilt in warm window light.',
    width: 1024,
    height: 1024,
    searchTerms: ['ragdoll', 'cat', 'kitten', 'quilt', 'fluffy', 'cute', 'AI artwork'],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'ai-siamese-linens-v1',
    shape: 'Square',
    name: 'Siamese linen nest · AI artwork',
    category: 'Animals',
    src: '/images/library/ai/ai-siamese-linens-v1.webp',
    alt: 'AI-generated realistic artwork of a blue-eyed Siamese cat resting its dark front paws over a wicker basket filled with folded towels.',
    width: 1024,
    height: 1024,
    searchTerms: ['Siamese', 'cat', 'kitten', 'linen', 'basket', 'cute', 'AI artwork'],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'ai-british-shorthair-rug-v1',
    shape: 'Square',
    name: 'British Shorthair ball patrol · AI artwork',
    category: 'Animals',
    src: '/images/library/ai/ai-british-shorthair-rug-v1.webp',
    alt: 'AI-generated realistic artwork of a round-faced gray British Shorthair kitten touching a cork ball on a coral and teal woven rug.',
    width: 1024,
    height: 1024,
    searchTerms: ['British Shorthair', 'cat', 'kitten', 'gray', 'ball', 'cute', 'AI artwork'],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'ai-bengal-garden-v1',
    shape: 'Square',
    name: 'Bengal garden explorer · AI artwork',
    category: 'Animals',
    src: '/images/library/ai/ai-bengal-garden-v1.webp',
    alt: 'AI-generated realistic artwork of a golden-brown spotted Bengal cat stepping along garden stones toward a purple flower.',
    width: 1024,
    height: 1024,
    searchTerms: ['Bengal', 'cat', 'kitten', 'garden', 'spotted', 'cute', 'AI artwork'],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'ai-tuxedo-chair-v1',
    shape: 'Square',
    name: 'Tuxedo chair mischief · AI artwork',
    category: 'Animals',
    src: '/images/library/ai/ai-tuxedo-chair-v1.webp',
    alt: 'AI-generated realistic artwork of a black-and-white tuxedo kitten lounging upside down over the edge of a teal armchair above a patterned rug.',
    width: 1024,
    height: 1024,
    searchTerms: ['tuxedo', 'cat', 'kitten', 'chair', 'funny', 'upside down', 'cute', 'AI artwork'],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'ai-calico-drawer-v1',
    shape: 'Square',
    name: 'Calico drawer hideaway · AI artwork',
    category: 'Animals',
    src: '/images/library/ai/ai-calico-drawer-v1.webp',
    alt: 'AI-generated realistic artwork of a calico kitten peeking from an open wooden drawer lined with folded yellow and blue clothes.',
    width: 1024,
    height: 1024,
    searchTerms: ['calico', 'cat', 'kitten', 'drawer', 'funny', 'cute', 'AI artwork'],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'ai-fluffy-white-kitten-v1',
    shape: 'Square',
    name: 'Snowy kitten blanket peek · AI artwork',
    category: 'Animals',
    src: '/images/library/ai/ai-fluffy-white-kitten-v1.webp',
    alt: 'AI-generated realistic artwork of a fluffy white blue-eyed kitten peeking over a sage-green blanket with its front paws resting on the edge.',
    width: 1024,
    height: 1024,
    searchTerms: ['white kitten', 'cat', 'kitten', 'fluffy', 'blanket', 'cute', 'AI artwork'],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'ai-abyssinian-stretch-v1',
    shape: 'Square',
    name: 'Abyssinian sunshine stretch · AI artwork',
    category: 'Animals',
    src: '/images/library/ai/ai-abyssinian-stretch-v1.webp',
    alt: 'AI-generated realistic artwork of a ruddy Abyssinian cat stretching its front paws along a sunlit wooden floor beside an indigo throw.',
    width: 1024,
    height: 1024,
    searchTerms: ['Abyssinian', 'cat', 'stretch', 'sunlight', 'cute', 'AI artwork'],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'ai-lion-savanna-v1',
    shape: 'Square',
    name: 'Savanna Guardian · AI artwork',
    category: 'Animals',
    src: '/images/library/ai/ai-lion-savanna-v1.webp',
    alt: 'AI-generated realistic artwork of a powerful male lion with a full mane standing on a low rock in golden savanna grassland.',
    width: 1024,
    height: 1024,
    searchTerms: ['lion', 'mane', 'savanna', 'wildlife', 'big cat', 'cute', 'AI artwork'],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'ai-elephant-family-v1',
    shape: 'Square',
    name: 'Elephant Family · AI artwork',
    category: 'Animals',
    src: '/images/library/ai/ai-elephant-family-v1.webp',
    alt: 'AI-generated realistic artwork of an adult elephant and its calf walking beside a shallow watering hole in a warm savanna landscape.',
    width: 1024,
    height: 1024,
    searchTerms: ['elephant', 'calf', 'family', 'wildlife', 'safari', 'cute', 'AI artwork'],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'ai-tiger-river-v1',
    shape: 'Square',
    name: 'Tiger River · AI artwork',
    category: 'Animals',
    src: '/images/library/ai/ai-tiger-river-v1.webp',
    alt: 'AI-generated realistic artwork of an orange-and-black tiger standing with its front paws in a shallow forest stream among stones and ferns.',
    width: 1024,
    height: 1024,
    searchTerms: ['tiger', 'river', 'stream', 'wildlife', 'big cat', 'cute', 'AI artwork'],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'ai-giant-panda-bamboo-v1',
    shape: 'Square',
    name: 'Bamboo Snack Break · AI artwork',
    category: 'Animals',
    src: '/images/library/ai/ai-giant-panda-bamboo-v1.webp',
    alt: 'AI-generated realistic artwork of a giant panda sitting in a bamboo grove and holding a leafy stalk in its front paws.',
    width: 1024,
    height: 1024,
    searchTerms: ['giant panda', 'bear', 'bamboo', 'wildlife', 'cute', 'AI artwork'],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'ai-red-panda-branch-v1',
    shape: 'Square',
    name: 'Autumn Branch Nap · AI artwork',
    category: 'Animals',
    src: '/images/library/ai/ai-red-panda-branch-v1.webp',
    alt: 'AI-generated realistic artwork of a red panda resting across a mossy tree branch with its long ringed tail surrounded by autumn leaves.',
    width: 1024,
    height: 1024,
    searchTerms: ['red panda', 'branch', 'autumn', 'wildlife', 'cute', 'AI artwork'],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
  {
    key: 'ai-bear-cub-creek-v1',
    shape: 'Square',
    name: 'Creekside Cub · AI artwork',
    category: 'Animals',
    src: '/images/library/ai/ai-bear-cub-creek-v1.webp',
    alt: 'AI-generated realistic artwork of a fluffy brown bear cub balancing on a broad mossy log beside a shallow woodland creek.',
    width: 1024,
    height: 1024,
    searchTerms: ['bear', 'cub', 'creek', 'wildlife', 'cute', 'AI artwork'],
    artworkCredit: {
      creator: 'SAL0MANder',
      generation: 'AI-generated',
      modifications: 'Resized; WebP format',
    },
  },
] as const
